/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 6.6.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QFrame *Middle;
    QComboBox *comboBox;
    QLabel *label_2;
    QLabel *label;
    QLabel *label_3;
    QLabel *weathericon_indicator;
    QFrame *UVindex_frame;
    QLabel *label_4;
    QLabel *uvindex_icon;
    QLabel *uvindex_value;
    QFrame *Windspeed_frame;
    QLabel *label_7;
    QLabel *windspeed_icon;
    QLabel *windspeed_value;
    QFrame *Humidity_frame;
    QLabel *label_5;
    QLabel *humidity_icon;
    QLabel *humidity_value;
    QFrame *Visibility_frame;
    QLabel *label_6;
    QLabel *visibility_icon;
    QLabel *visibility_value;
    QFrame *feelslike_frame;
    QLabel *label_9;
    QLabel *feelslike_icon;
    QLabel *feelslike_value;
    QFrame *pressure_frame;
    QLabel *label_10;
    QLabel *pressure_icon;
    QLabel *pressure_value;
    QFrame *chanceofrain_frame;
    QLabel *label_11;
    QLabel *chanceofrain_icon;
    QLabel *chanceofrain_value;
    QFrame *pressure_frame_2;
    QLabel *label_12;
    QLabel *sunset_icon;
    QLabel *sunset_value;
    QFrame *Left;
    QPushButton *Home_button;
    QPushButton *Search_button;
    QPushButton *Map_button;
    QPushButton *Setting_button;
    QPushButton *Dashboard_button;
    QFrame *Right;
    QFrame *todayprediction_frame;
    QLabel *todaysWeather_label;
    QLabel *weathericon_indicator_at_six;
    QLabel *weathericon_indicator_at_nine;
    QLabel *weathericon_indicator_at_twelve;
    QLabel *timeat6am;
    QLabel *temperatureatsix;
    QLabel *timeat9am;
    QLabel *temperatureatnine;
    QLabel *timeat12pm;
    QLabel *temperatureattwelve;
    QFrame *sevenday_frame;
    QLabel *sevenDay_label;
    QLabel *monday_label;
    QLabel *tuesday_label;
    QLabel *wednesday_label;
    QLabel *thursday_label;
    QLabel *friday_label;
    QLabel *saturday_label;
    QLabel *sunday_label;
    QLabel *monday_icon;
    QLabel *tuesday_icon;
    QLabel *wednesday_icon;
    QLabel *thursday_icon;
    QLabel *friday_icon;
    QLabel *saturday_icon;
    QLabel *sunday_icon;
    QLabel *moday_description;
    QLabel *tuesday_description;
    QLabel *wednesday_description;
    QLabel *thursday_description;
    QLabel *friday_desctiption;
    QLabel *saturday_description;
    QLabel *sunday_description;
    QLabel *highlow_label;
    QLabel *moday_temp;
    QLabel *tuesday_temp;
    QLabel *wednesday_temp;
    QLabel *thursday_temp;
    QLabel *friday_temp;
    QLabel *saturday_temp;
    QLabel *sunday_temp;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName("MainWindow");
        MainWindow->resize(1070, 686);
        MainWindow->setAutoFillBackground(false);
        MainWindow->setStyleSheet(QString::fromUtf8("background-color: rgb(20,20,20);"));
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName("centralwidget");
        Middle = new QFrame(centralwidget);
        Middle->setObjectName("Middle");
        Middle->setGeometry(QRect(110, 10, 475, 631));
        Middle->setMaximumSize(QSize(475, 16777215));
        comboBox = new QComboBox(Middle);
        comboBox->setObjectName("comboBox");
        comboBox->setGeometry(QRect(0, 10, 461, 21));
        comboBox->setMaximumSize(QSize(16777215, 16777215));
        comboBox->setStyleSheet(QString::fromUtf8("alternate-background-color: rgb(0, 0, 0);\n"
"selection-color: rgb(0, 0, 0);\n"
"color: rgb(97, 97, 97);"));
        comboBox->setEditable(true);
        label_2 = new QLabel(Middle);
        label_2->setObjectName("label_2");
        label_2->setGeometry(QRect(30, 80, 131, 21));
        QFont font;
        font.setFamilies({QString::fromUtf8("Arial Unicode MS")});
        font.setPointSize(14);
        font.setBold(false);
        font.setKerning(true);
        label_2->setFont(font);
        label_2->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        label = new QLabel(Middle);
        label->setObjectName("label");
        label->setGeometry(QRect(30, 50, 221, 31));
        QFont font1;
        font1.setFamilies({QString::fromUtf8("Arial Unicode MS")});
        font1.setPointSize(22);
        font1.setBold(true);
        label->setFont(font1);
        label->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        label_3 = new QLabel(Middle);
        label_3->setObjectName("label_3");
        label_3->setGeometry(QRect(20, 170, 241, 51));
        QFont font2;
        font2.setFamilies({QString::fromUtf8("Arial")});
        font2.setPointSize(36);
        font2.setBold(true);
        label_3->setFont(font2);
        label_3->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_3->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        weathericon_indicator = new QLabel(Middle);
        weathericon_indicator->setObjectName("weathericon_indicator");
        weathericon_indicator->setGeometry(QRect(260, 60, 161, 161));
        weathericon_indicator->setPixmap(QPixmap(QString::fromUtf8("../Icons/sun_869869.png")));
        weathericon_indicator->setScaledContents(true);
        UVindex_frame = new QFrame(Middle);
        UVindex_frame->setObjectName("UVindex_frame");
        UVindex_frame->setGeometry(QRect(10, 240, 211, 91));
        UVindex_frame->setMouseTracking(true);
        UVindex_frame->setTabletTracking(true);
        UVindex_frame->setStyleSheet(QString::fromUtf8("background-color: rgb(53, 53, 53);\n"
"border-radius: 10px;"));
        label_4 = new QLabel(UVindex_frame);
        label_4->setObjectName("label_4");
        label_4->setGeometry(QRect(50, 10, 58, 16));
        QFont font3;
        font3.setFamilies({QString::fromUtf8("Arial")});
        label_4->setFont(font3);
        label_4->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        uvindex_icon = new QLabel(UVindex_frame);
        uvindex_icon->setObjectName("uvindex_icon");
        uvindex_icon->setGeometry(QRect(20, 10, 21, 21));
        uvindex_icon->setPixmap(QPixmap(QString::fromUtf8("../Icons/uvindex_icon.png")));
        uvindex_icon->setScaledContents(true);
        uvindex_value = new QLabel(UVindex_frame);
        uvindex_value->setObjectName("uvindex_value");
        uvindex_value->setGeometry(QRect(50, 50, 61, 16));
        QFont font4;
        font4.setFamilies({QString::fromUtf8("Arial")});
        font4.setPointSize(18);
        font4.setBold(true);
        uvindex_value->setFont(font4);
        uvindex_value->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        Windspeed_frame = new QFrame(Middle);
        Windspeed_frame->setObjectName("Windspeed_frame");
        Windspeed_frame->setGeometry(QRect(240, 240, 211, 91));
        Windspeed_frame->setMouseTracking(true);
        Windspeed_frame->setStyleSheet(QString::fromUtf8("background-color: rgb(53, 53, 53);\n"
"border-radius: 10px;"));
        label_7 = new QLabel(Windspeed_frame);
        label_7->setObjectName("label_7");
        label_7->setGeometry(QRect(50, 10, 71, 16));
        label_7->setFont(font3);
        label_7->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        windspeed_icon = new QLabel(Windspeed_frame);
        windspeed_icon->setObjectName("windspeed_icon");
        windspeed_icon->setGeometry(QRect(20, 10, 21, 21));
        windspeed_icon->setPixmap(QPixmap(QString::fromUtf8("../Icons/windspeed.png")));
        windspeed_icon->setScaledContents(true);
        windspeed_value = new QLabel(Windspeed_frame);
        windspeed_value->setObjectName("windspeed_value");
        windspeed_value->setGeometry(QRect(50, 50, 111, 16));
        windspeed_value->setFont(font4);
        windspeed_value->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        Humidity_frame = new QFrame(Middle);
        Humidity_frame->setObjectName("Humidity_frame");
        Humidity_frame->setGeometry(QRect(10, 340, 211, 81));
        Humidity_frame->setMouseTracking(true);
        Humidity_frame->setStyleSheet(QString::fromUtf8("background-color: rgb(53, 53, 53);\n"
"border-radius: 10px;"));
        label_5 = new QLabel(Humidity_frame);
        label_5->setObjectName("label_5");
        label_5->setGeometry(QRect(50, 10, 58, 16));
        label_5->setFont(font3);
        label_5->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        humidity_icon = new QLabel(Humidity_frame);
        humidity_icon->setObjectName("humidity_icon");
        humidity_icon->setGeometry(QRect(20, 10, 21, 21));
        humidity_icon->setPixmap(QPixmap(QString::fromUtf8("../Icons/humidity_icon.png")));
        humidity_icon->setScaledContents(true);
        humidity_value = new QLabel(Humidity_frame);
        humidity_value->setObjectName("humidity_value");
        humidity_value->setGeometry(QRect(50, 40, 71, 16));
        humidity_value->setFont(font4);
        humidity_value->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        Visibility_frame = new QFrame(Middle);
        Visibility_frame->setObjectName("Visibility_frame");
        Visibility_frame->setGeometry(QRect(240, 340, 211, 81));
        Visibility_frame->setMouseTracking(true);
        Visibility_frame->setStyleSheet(QString::fromUtf8("background-color: rgb(53, 53, 53);\n"
"border-radius: 10px;"));
        label_6 = new QLabel(Visibility_frame);
        label_6->setObjectName("label_6");
        label_6->setGeometry(QRect(50, 10, 58, 16));
        label_6->setFont(font3);
        label_6->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        visibility_icon = new QLabel(Visibility_frame);
        visibility_icon->setObjectName("visibility_icon");
        visibility_icon->setGeometry(QRect(20, 10, 21, 21));
        visibility_icon->setPixmap(QPixmap(QString::fromUtf8("../Icons/visibility_icon.png")));
        visibility_icon->setScaledContents(true);
        visibility_value = new QLabel(Visibility_frame);
        visibility_value->setObjectName("visibility_value");
        visibility_value->setGeometry(QRect(50, 30, 91, 16));
        visibility_value->setFont(font4);
        visibility_value->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        feelslike_frame = new QFrame(Middle);
        feelslike_frame->setObjectName("feelslike_frame");
        feelslike_frame->setGeometry(QRect(10, 430, 211, 81));
        feelslike_frame->setMouseTracking(true);
        feelslike_frame->setStyleSheet(QString::fromUtf8("background-color: rgb(53, 53, 53);\n"
"border-radius: 10px;"));
        label_9 = new QLabel(feelslike_frame);
        label_9->setObjectName("label_9");
        label_9->setGeometry(QRect(50, 10, 58, 16));
        label_9->setFont(font3);
        label_9->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        feelslike_icon = new QLabel(feelslike_frame);
        feelslike_icon->setObjectName("feelslike_icon");
        feelslike_icon->setGeometry(QRect(20, 10, 21, 21));
        feelslike_icon->setPixmap(QPixmap(QString::fromUtf8("../Icons/feelslike_icon.png")));
        feelslike_icon->setScaledContents(true);
        feelslike_value = new QLabel(feelslike_frame);
        feelslike_value->setObjectName("feelslike_value");
        feelslike_value->setGeometry(QRect(50, 40, 71, 16));
        feelslike_value->setFont(font4);
        feelslike_value->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        pressure_frame = new QFrame(Middle);
        pressure_frame->setObjectName("pressure_frame");
        pressure_frame->setGeometry(QRect(10, 520, 211, 81));
        pressure_frame->setMouseTracking(true);
        pressure_frame->setStyleSheet(QString::fromUtf8("background-color: rgb(53, 53, 53);\n"
"border-radius: 10px;"));
        label_10 = new QLabel(pressure_frame);
        label_10->setObjectName("label_10");
        label_10->setGeometry(QRect(50, 10, 58, 16));
        label_10->setFont(font3);
        label_10->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        pressure_icon = new QLabel(pressure_frame);
        pressure_icon->setObjectName("pressure_icon");
        pressure_icon->setGeometry(QRect(20, 10, 21, 21));
        pressure_icon->setPixmap(QPixmap(QString::fromUtf8("../Icons/pressure_icon.png")));
        pressure_icon->setScaledContents(true);
        pressure_value = new QLabel(pressure_frame);
        pressure_value->setObjectName("pressure_value");
        pressure_value->setGeometry(QRect(50, 40, 101, 16));
        pressure_value->setFont(font4);
        pressure_value->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        chanceofrain_frame = new QFrame(Middle);
        chanceofrain_frame->setObjectName("chanceofrain_frame");
        chanceofrain_frame->setGeometry(QRect(240, 430, 211, 81));
        chanceofrain_frame->setMouseTracking(true);
        chanceofrain_frame->setStyleSheet(QString::fromUtf8("background-color: rgb(53, 53, 53);\n"
"border-radius: 10px;"));
        label_11 = new QLabel(chanceofrain_frame);
        label_11->setObjectName("label_11");
        label_11->setGeometry(QRect(50, 10, 91, 16));
        label_11->setFont(font3);
        label_11->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        chanceofrain_icon = new QLabel(chanceofrain_frame);
        chanceofrain_icon->setObjectName("chanceofrain_icon");
        chanceofrain_icon->setGeometry(QRect(20, 10, 21, 21));
        chanceofrain_icon->setPixmap(QPixmap(QString::fromUtf8("../Icons/chanceofrain_icon.png")));
        chanceofrain_icon->setScaledContents(true);
        chanceofrain_value = new QLabel(chanceofrain_frame);
        chanceofrain_value->setObjectName("chanceofrain_value");
        chanceofrain_value->setGeometry(QRect(50, 40, 71, 16));
        chanceofrain_value->setFont(font4);
        chanceofrain_value->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        pressure_frame_2 = new QFrame(Middle);
        pressure_frame_2->setObjectName("pressure_frame_2");
        pressure_frame_2->setGeometry(QRect(240, 520, 211, 81));
        pressure_frame_2->setMouseTracking(true);
        pressure_frame_2->setStyleSheet(QString::fromUtf8("background-color: rgb(53, 53, 53);\n"
"border-radius: 10px;"));
        label_12 = new QLabel(pressure_frame_2);
        label_12->setObjectName("label_12");
        label_12->setGeometry(QRect(50, 10, 58, 16));
        label_12->setFont(font3);
        label_12->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        sunset_icon = new QLabel(pressure_frame_2);
        sunset_icon->setObjectName("sunset_icon");
        sunset_icon->setGeometry(QRect(20, 10, 21, 21));
        sunset_icon->setPixmap(QPixmap(QString::fromUtf8("../Icons/sunset_icon.png")));
        sunset_icon->setScaledContents(true);
        sunset_value = new QLabel(pressure_frame_2);
        sunset_value->setObjectName("sunset_value");
        sunset_value->setGeometry(QRect(50, 40, 101, 16));
        sunset_value->setFont(font4);
        sunset_value->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        Left = new QFrame(centralwidget);
        Left->setObjectName("Left");
        Left->setGeometry(QRect(10, 10, 100, 631));
        Left->setMaximumSize(QSize(100, 16777215));
        Left->setFrameShape(QFrame::NoFrame);
        Left->setFrameShadow(QFrame::Raised);
        Home_button = new QPushButton(Left);
        Home_button->setObjectName("Home_button");
        Home_button->setGeometry(QRect(12, 43, 76, 76));
        Home_button->setMinimumSize(QSize(50, 50));
        Home_button->setFont(font3);
        Home_button->setLayoutDirection(Qt::LeftToRight);
        Home_button->setAutoFillBackground(false);
        QIcon icon;
        icon.addFile(QString::fromUtf8("../Icons/Home.png"), QSize(), QIcon::Normal, QIcon::Off);
        Home_button->setIcon(icon);
        Home_button->setIconSize(QSize(60, 60));
        Home_button->setFlat(true);
        Search_button = new QPushButton(Left);
        Search_button->setObjectName("Search_button");
        Search_button->setGeometry(QRect(20, 190, 63, 50));
        Search_button->setMinimumSize(QSize(50, 50));
        Search_button->setFont(font3);
        Search_button->setLayoutDirection(Qt::LeftToRight);
        Search_button->setAutoFillBackground(false);
        QIcon icon1;
        icon1.addFile(QString::fromUtf8("../Icons/search.png"), QSize(), QIcon::Normal, QIcon::Off);
        Search_button->setIcon(icon1);
        Search_button->setIconSize(QSize(30, 30));
        Search_button->setFlat(true);
        Map_button = new QPushButton(Left);
        Map_button->setObjectName("Map_button");
        Map_button->setGeometry(QRect(20, 250, 63, 50));
        Map_button->setMinimumSize(QSize(50, 50));
        Map_button->setFont(font3);
        Map_button->setLayoutDirection(Qt::LeftToRight);
        Map_button->setAutoFillBackground(false);
        QIcon icon2;
        icon2.addFile(QString::fromUtf8("../Icons/map.png"), QSize(), QIcon::Normal, QIcon::Off);
        Map_button->setIcon(icon2);
        Map_button->setIconSize(QSize(30, 30));
        Map_button->setFlat(true);
        Setting_button = new QPushButton(Left);
        Setting_button->setObjectName("Setting_button");
        Setting_button->setGeometry(QRect(20, 310, 61, 51));
        Setting_button->setMinimumSize(QSize(50, 50));
        Setting_button->setFont(font3);
        Setting_button->setLayoutDirection(Qt::LeftToRight);
        Setting_button->setAutoFillBackground(false);
        QIcon icon3;
        icon3.addFile(QString::fromUtf8("../Icons/settings.png"), QSize(), QIcon::Normal, QIcon::Off);
        Setting_button->setIcon(icon3);
        Setting_button->setIconSize(QSize(25, 25));
        Setting_button->setFlat(true);
        Dashboard_button = new QPushButton(Left);
        Dashboard_button->setObjectName("Dashboard_button");
        Dashboard_button->setGeometry(QRect(20, 130, 63, 50));
        Dashboard_button->setMinimumSize(QSize(50, 50));
        Dashboard_button->setFont(font3);
        Dashboard_button->setLayoutDirection(Qt::LeftToRight);
        Dashboard_button->setAutoFillBackground(false);
        Dashboard_button->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        QIcon icon4;
        icon4.addFile(QString::fromUtf8("../Icons/dashboard.png"), QSize(), QIcon::Normal, QIcon::Off);
        Dashboard_button->setIcon(icon4);
        Dashboard_button->setIconSize(QSize(30, 30));
        Dashboard_button->setFlat(true);
        Right = new QFrame(centralwidget);
        Right->setObjectName("Right");
        Right->setGeometry(QRect(580, 10, 475, 631));
        Right->setMaximumSize(QSize(475, 16777215));
        Right->setFrameShape(QFrame::NoFrame);
        Right->setFrameShadow(QFrame::Raised);
        todayprediction_frame = new QFrame(Right);
        todayprediction_frame->setObjectName("todayprediction_frame");
        todayprediction_frame->setGeometry(QRect(20, 60, 441, 161));
        todayprediction_frame->setStyleSheet(QString::fromUtf8("background-color: rgb(53, 53, 53);\n"
"border-radius: 10px;"));
        todayprediction_frame->setFrameShape(QFrame::StyledPanel);
        todayprediction_frame->setFrameShadow(QFrame::Raised);
        todaysWeather_label = new QLabel(todayprediction_frame);
        todaysWeather_label->setObjectName("todaysWeather_label");
        todaysWeather_label->setGeometry(QRect(30, 20, 181, 16));
        QFont font5;
        font5.setFamilies({QString::fromUtf8("Arial")});
        font5.setBold(true);
        todaysWeather_label->setFont(font5);
        todaysWeather_label->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        weathericon_indicator_at_six = new QLabel(todayprediction_frame);
        weathericon_indicator_at_six->setObjectName("weathericon_indicator_at_six");
        weathericon_indicator_at_six->setGeometry(QRect(40, 70, 51, 51));
        weathericon_indicator_at_six->setPixmap(QPixmap(QString::fromUtf8("../Icons/cloudymigthrain_icon.png")));
        weathericon_indicator_at_six->setScaledContents(true);
        weathericon_indicator_at_nine = new QLabel(todayprediction_frame);
        weathericon_indicator_at_nine->setObjectName("weathericon_indicator_at_nine");
        weathericon_indicator_at_nine->setGeometry(QRect(170, 70, 51, 51));
        weathericon_indicator_at_nine->setPixmap(QPixmap(QString::fromUtf8("../Icons/cloudy_icon.png")));
        weathericon_indicator_at_nine->setScaledContents(true);
        weathericon_indicator_at_twelve = new QLabel(todayprediction_frame);
        weathericon_indicator_at_twelve->setObjectName("weathericon_indicator_at_twelve");
        weathericon_indicator_at_twelve->setGeometry(QRect(300, 70, 51, 51));
        weathericon_indicator_at_twelve->setPixmap(QPixmap(QString::fromUtf8("../Icons/sun_869869.png")));
        weathericon_indicator_at_twelve->setScaledContents(true);
        timeat6am = new QLabel(todayprediction_frame);
        timeat6am->setObjectName("timeat6am");
        timeat6am->setGeometry(QRect(100, 80, 61, 16));
        timeat6am->setFont(font5);
        timeat6am->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        temperatureatsix = new QLabel(todayprediction_frame);
        temperatureatsix->setObjectName("temperatureatsix");
        temperatureatsix->setGeometry(QRect(110, 100, 41, 16));
        temperatureatsix->setFont(font5);
        temperatureatsix->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        timeat9am = new QLabel(todayprediction_frame);
        timeat9am->setObjectName("timeat9am");
        timeat9am->setGeometry(QRect(230, 80, 61, 16));
        timeat9am->setFont(font5);
        timeat9am->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        temperatureatnine = new QLabel(todayprediction_frame);
        temperatureatnine->setObjectName("temperatureatnine");
        temperatureatnine->setGeometry(QRect(240, 100, 41, 16));
        temperatureatnine->setFont(font5);
        temperatureatnine->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        timeat12pm = new QLabel(todayprediction_frame);
        timeat12pm->setObjectName("timeat12pm");
        timeat12pm->setGeometry(QRect(360, 80, 61, 16));
        timeat12pm->setFont(font5);
        timeat12pm->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        temperatureattwelve = new QLabel(todayprediction_frame);
        temperatureattwelve->setObjectName("temperatureattwelve");
        temperatureattwelve->setGeometry(QRect(370, 100, 41, 16));
        temperatureattwelve->setFont(font5);
        temperatureattwelve->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        sevenday_frame = new QFrame(Right);
        sevenday_frame->setObjectName("sevenday_frame");
        sevenday_frame->setGeometry(QRect(20, 240, 441, 361));
        sevenday_frame->setStyleSheet(QString::fromUtf8("background-color: rgb(53, 53, 53);\n"
"border-radius: 10px;\n"
""));
        sevenday_frame->setFrameShape(QFrame::StyledPanel);
        sevenday_frame->setFrameShadow(QFrame::Raised);
        sevenDay_label = new QLabel(sevenday_frame);
        sevenDay_label->setObjectName("sevenDay_label");
        sevenDay_label->setGeometry(QRect(30, 20, 181, 16));
        sevenDay_label->setFont(font5);
        sevenDay_label->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        monday_label = new QLabel(sevenday_frame);
        monday_label->setObjectName("monday_label");
        monday_label->setGeometry(QRect(30, 60, 71, 16));
        QFont font6;
        font6.setFamilies({QString::fromUtf8("Arial")});
        font6.setBold(false);
        monday_label->setFont(font6);
        monday_label->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        tuesday_label = new QLabel(sevenday_frame);
        tuesday_label->setObjectName("tuesday_label");
        tuesday_label->setGeometry(QRect(30, 100, 71, 16));
        tuesday_label->setFont(font6);
        tuesday_label->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        wednesday_label = new QLabel(sevenday_frame);
        wednesday_label->setObjectName("wednesday_label");
        wednesday_label->setGeometry(QRect(30, 140, 81, 16));
        wednesday_label->setFont(font6);
        wednesday_label->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        thursday_label = new QLabel(sevenday_frame);
        thursday_label->setObjectName("thursday_label");
        thursday_label->setGeometry(QRect(30, 180, 71, 16));
        thursday_label->setFont(font6);
        thursday_label->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        friday_label = new QLabel(sevenday_frame);
        friday_label->setObjectName("friday_label");
        friday_label->setGeometry(QRect(30, 220, 71, 16));
        friday_label->setFont(font6);
        friday_label->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        saturday_label = new QLabel(sevenday_frame);
        saturday_label->setObjectName("saturday_label");
        saturday_label->setGeometry(QRect(30, 260, 71, 16));
        saturday_label->setFont(font6);
        saturday_label->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        sunday_label = new QLabel(sevenday_frame);
        sunday_label->setObjectName("sunday_label");
        sunday_label->setGeometry(QRect(30, 300, 71, 16));
        sunday_label->setFont(font6);
        sunday_label->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        monday_icon = new QLabel(sevenday_frame);
        monday_icon->setObjectName("monday_icon");
        monday_icon->setGeometry(QRect(120, 50, 31, 31));
        monday_icon->setPixmap(QPixmap(QString::fromUtf8("../Icons/sun_869869.png")));
        monday_icon->setScaledContents(true);
        tuesday_icon = new QLabel(sevenday_frame);
        tuesday_icon->setObjectName("tuesday_icon");
        tuesday_icon->setGeometry(QRect(120, 90, 31, 31));
        tuesday_icon->setPixmap(QPixmap(QString::fromUtf8("../Icons/sun_869869.png")));
        tuesday_icon->setScaledContents(true);
        wednesday_icon = new QLabel(sevenday_frame);
        wednesday_icon->setObjectName("wednesday_icon");
        wednesday_icon->setGeometry(QRect(120, 130, 31, 31));
        wednesday_icon->setPixmap(QPixmap(QString::fromUtf8("../Icons/sun_869869.png")));
        wednesday_icon->setScaledContents(true);
        thursday_icon = new QLabel(sevenday_frame);
        thursday_icon->setObjectName("thursday_icon");
        thursday_icon->setGeometry(QRect(120, 170, 31, 31));
        thursday_icon->setPixmap(QPixmap(QString::fromUtf8("../Icons/cloudy_icon.png")));
        thursday_icon->setScaledContents(true);
        friday_icon = new QLabel(sevenday_frame);
        friday_icon->setObjectName("friday_icon");
        friday_icon->setGeometry(QRect(120, 210, 31, 31));
        friday_icon->setPixmap(QPixmap(QString::fromUtf8("../Icons/cloudy_icon.png")));
        friday_icon->setScaledContents(true);
        saturday_icon = new QLabel(sevenday_frame);
        saturday_icon->setObjectName("saturday_icon");
        saturday_icon->setGeometry(QRect(120, 250, 31, 31));
        saturday_icon->setPixmap(QPixmap(QString::fromUtf8("../Icons/cloudymigthrain_icon.png")));
        saturday_icon->setScaledContents(true);
        sunday_icon = new QLabel(sevenday_frame);
        sunday_icon->setObjectName("sunday_icon");
        sunday_icon->setGeometry(QRect(120, 290, 31, 31));
        sunday_icon->setPixmap(QPixmap(QString::fromUtf8("../Icons/sun_869869.png")));
        sunday_icon->setScaledContents(true);
        moday_description = new QLabel(sevenday_frame);
        moday_description->setObjectName("moday_description");
        moday_description->setGeometry(QRect(210, 60, 71, 16));
        moday_description->setFont(font5);
        moday_description->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        tuesday_description = new QLabel(sevenday_frame);
        tuesday_description->setObjectName("tuesday_description");
        tuesday_description->setGeometry(QRect(210, 100, 71, 16));
        tuesday_description->setFont(font5);
        tuesday_description->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        wednesday_description = new QLabel(sevenday_frame);
        wednesday_description->setObjectName("wednesday_description");
        wednesday_description->setGeometry(QRect(210, 140, 71, 16));
        wednesday_description->setFont(font5);
        wednesday_description->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        thursday_description = new QLabel(sevenday_frame);
        thursday_description->setObjectName("thursday_description");
        thursday_description->setGeometry(QRect(210, 180, 71, 16));
        thursday_description->setFont(font5);
        thursday_description->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        friday_desctiption = new QLabel(sevenday_frame);
        friday_desctiption->setObjectName("friday_desctiption");
        friday_desctiption->setGeometry(QRect(210, 220, 71, 16));
        friday_desctiption->setFont(font5);
        friday_desctiption->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        saturday_description = new QLabel(sevenday_frame);
        saturday_description->setObjectName("saturday_description");
        saturday_description->setGeometry(QRect(210, 260, 71, 16));
        saturday_description->setFont(font5);
        saturday_description->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        sunday_description = new QLabel(sevenday_frame);
        sunday_description->setObjectName("sunday_description");
        sunday_description->setGeometry(QRect(210, 300, 71, 16));
        sunday_description->setFont(font5);
        sunday_description->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        highlow_label = new QLabel(sevenday_frame);
        highlow_label->setObjectName("highlow_label");
        highlow_label->setGeometry(QRect(310, 30, 71, 16));
        highlow_label->setFont(font5);
        highlow_label->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        moday_temp = new QLabel(sevenday_frame);
        moday_temp->setObjectName("moday_temp");
        moday_temp->setGeometry(QRect(310, 60, 61, 20));
        moday_temp->setFont(font6);
        moday_temp->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        moday_temp->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        tuesday_temp = new QLabel(sevenday_frame);
        tuesday_temp->setObjectName("tuesday_temp");
        tuesday_temp->setGeometry(QRect(310, 100, 61, 20));
        tuesday_temp->setFont(font6);
        tuesday_temp->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        tuesday_temp->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        wednesday_temp = new QLabel(sevenday_frame);
        wednesday_temp->setObjectName("wednesday_temp");
        wednesday_temp->setGeometry(QRect(310, 140, 61, 20));
        wednesday_temp->setFont(font6);
        wednesday_temp->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        wednesday_temp->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        thursday_temp = new QLabel(sevenday_frame);
        thursday_temp->setObjectName("thursday_temp");
        thursday_temp->setGeometry(QRect(310, 180, 61, 20));
        thursday_temp->setFont(font6);
        thursday_temp->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        thursday_temp->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        friday_temp = new QLabel(sevenday_frame);
        friday_temp->setObjectName("friday_temp");
        friday_temp->setGeometry(QRect(310, 220, 61, 20));
        friday_temp->setFont(font6);
        friday_temp->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        friday_temp->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        saturday_temp = new QLabel(sevenday_frame);
        saturday_temp->setObjectName("saturday_temp");
        saturday_temp->setGeometry(QRect(310, 260, 61, 20));
        saturday_temp->setFont(font6);
        saturday_temp->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        saturday_temp->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        sunday_temp = new QLabel(sevenday_frame);
        sunday_temp->setObjectName("sunday_temp");
        sunday_temp->setGeometry(QRect(310, 300, 61, 20));
        sunday_temp->setFont(font6);
        sunday_temp->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        sunday_temp->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        MainWindow->setCentralWidget(centralwidget);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "MainWindow", nullptr));
        comboBox->setCurrentText(QString());
        comboBox->setPlaceholderText(QCoreApplication::translate("MainWindow", "Enter Location (ex. Bangkok)", nullptr));
        label_2->setText(QCoreApplication::translate("MainWindow", "Chance of Rain: 0%", nullptr));
        label->setText(QCoreApplication::translate("MainWindow", "Weather Forecast for", nullptr));
        label_3->setText(QCoreApplication::translate("MainWindow", "Temperature:", nullptr));
        weathericon_indicator->setText(QString());
        label_4->setText(QCoreApplication::translate("MainWindow", "UV index", nullptr));
        uvindex_icon->setText(QString());
        uvindex_value->setText(QCoreApplication::translate("MainWindow", "3", nullptr));
        label_7->setText(QCoreApplication::translate("MainWindow", "Wind Speed", nullptr));
        windspeed_icon->setText(QString());
        windspeed_value->setText(QCoreApplication::translate("MainWindow", "0.2 km/h", nullptr));
        label_5->setText(QCoreApplication::translate("MainWindow", "Humidity", nullptr));
        humidity_icon->setText(QString());
        humidity_value->setText(QCoreApplication::translate("MainWindow", "3", nullptr));
        label_6->setText(QCoreApplication::translate("MainWindow", "Visibility", nullptr));
        visibility_icon->setText(QString());
        visibility_value->setText(QCoreApplication::translate("MainWindow", "12 km", nullptr));
        label_9->setText(QCoreApplication::translate("MainWindow", "Feels like", nullptr));
        feelslike_icon->setText(QString());
        feelslike_value->setText(QCoreApplication::translate("MainWindow", "30\302\260c", nullptr));
        label_10->setText(QCoreApplication::translate("MainWindow", "Pressure", nullptr));
        pressure_icon->setText(QString());
        pressure_value->setText(QCoreApplication::translate("MainWindow", "1008 hPa", nullptr));
        label_11->setText(QCoreApplication::translate("MainWindow", "Chance of rain", nullptr));
        chanceofrain_icon->setText(QString());
        chanceofrain_value->setText(QCoreApplication::translate("MainWindow", "0%", nullptr));
        label_12->setText(QCoreApplication::translate("MainWindow", "Sunset", nullptr));
        sunset_icon->setText(QString());
        sunset_value->setText(QCoreApplication::translate("MainWindow", "20:58", nullptr));
#if QT_CONFIG(tooltip)
        Home_button->setToolTip(QCoreApplication::translate("MainWindow", "access for interactive map", nullptr));
#endif // QT_CONFIG(tooltip)
        Home_button->setText(QString());
#if QT_CONFIG(tooltip)
        Search_button->setToolTip(QCoreApplication::translate("MainWindow", "access for interactive map", nullptr));
#endif // QT_CONFIG(tooltip)
        Search_button->setText(QString());
#if QT_CONFIG(tooltip)
        Map_button->setToolTip(QCoreApplication::translate("MainWindow", "access for interactive map", nullptr));
#endif // QT_CONFIG(tooltip)
        Map_button->setText(QString());
#if QT_CONFIG(tooltip)
        Setting_button->setToolTip(QCoreApplication::translate("MainWindow", "access for interactive map", nullptr));
#endif // QT_CONFIG(tooltip)
        Setting_button->setText(QString());
#if QT_CONFIG(tooltip)
        Dashboard_button->setToolTip(QCoreApplication::translate("MainWindow", "access for interactive map", nullptr));
#endif // QT_CONFIG(tooltip)
        Dashboard_button->setText(QString());
        todaysWeather_label->setText(QCoreApplication::translate("MainWindow", "Today's Weather Prediciton", nullptr));
        weathericon_indicator_at_six->setText(QString());
        weathericon_indicator_at_nine->setText(QString());
        weathericon_indicator_at_twelve->setText(QString());
        timeat6am->setText(QCoreApplication::translate("MainWindow", "6:00 AM", nullptr));
        temperatureatsix->setText(QCoreApplication::translate("MainWindow", "25\302\260c", nullptr));
        timeat9am->setText(QCoreApplication::translate("MainWindow", "9:00 AM", nullptr));
        temperatureatnine->setText(QCoreApplication::translate("MainWindow", "25\302\260c", nullptr));
        timeat12pm->setText(QCoreApplication::translate("MainWindow", "12:00 PM", nullptr));
        temperatureattwelve->setText(QCoreApplication::translate("MainWindow", "25\302\260c", nullptr));
        sevenDay_label->setText(QCoreApplication::translate("MainWindow", "7-Day Forecast", nullptr));
        monday_label->setText(QCoreApplication::translate("MainWindow", "Monday", nullptr));
        tuesday_label->setText(QCoreApplication::translate("MainWindow", "Tuesday", nullptr));
        wednesday_label->setText(QCoreApplication::translate("MainWindow", "Wednesday", nullptr));
        thursday_label->setText(QCoreApplication::translate("MainWindow", "Thursday", nullptr));
        friday_label->setText(QCoreApplication::translate("MainWindow", "Friday", nullptr));
        saturday_label->setText(QCoreApplication::translate("MainWindow", "Saturday", nullptr));
        sunday_label->setText(QCoreApplication::translate("MainWindow", "Sunday", nullptr));
        monday_icon->setText(QString());
        tuesday_icon->setText(QString());
        wednesday_icon->setText(QString());
        thursday_icon->setText(QString());
        friday_icon->setText(QString());
        saturday_icon->setText(QString());
        sunday_icon->setText(QString());
        moday_description->setText(QCoreApplication::translate("MainWindow", "Sunny", nullptr));
        tuesday_description->setText(QCoreApplication::translate("MainWindow", "Sunny", nullptr));
        wednesday_description->setText(QCoreApplication::translate("MainWindow", "Sunny", nullptr));
        thursday_description->setText(QCoreApplication::translate("MainWindow", "Sunny", nullptr));
        friday_desctiption->setText(QCoreApplication::translate("MainWindow", "Sunny", nullptr));
        saturday_description->setText(QCoreApplication::translate("MainWindow", "Sunny", nullptr));
        sunday_description->setText(QCoreApplication::translate("MainWindow", "Sunny", nullptr));
        highlow_label->setText(QCoreApplication::translate("MainWindow", "High/Low", nullptr));
        moday_temp->setText(QCoreApplication::translate("MainWindow", "37/21", nullptr));
        tuesday_temp->setText(QCoreApplication::translate("MainWindow", "37/21", nullptr));
        wednesday_temp->setText(QCoreApplication::translate("MainWindow", "37/21", nullptr));
        thursday_temp->setText(QCoreApplication::translate("MainWindow", "37/21", nullptr));
        friday_temp->setText(QCoreApplication::translate("MainWindow", "37/21", nullptr));
        saturday_temp->setText(QCoreApplication::translate("MainWindow", "37/21", nullptr));
        sunday_temp->setText(QCoreApplication::translate("MainWindow", "37/21", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
